package it.uniba.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

public class LoginRequestGUI implements Runnable {
    private boolean isdataConfirmed = false;

    private JPanel mainPanel;
    private JTextField textFieldCredential;
    private JButton confirmButton;
    private JLabel requestedValue;

    private JFrame frame;

    private String stringUserResponse = "error";

    private final int numMaxChar = 40; //costante numero massimo caratteri textArea

    private final int threadSleep = 500;

    public LoginRequestGUI(final String title) {
        this.startGUI(title);
        confirmButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(final ActionEvent e) {
                confirmCredential();
            }
        });

        textFieldCredential.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(final KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    confirmCredential();
                }
            }
        });

        /**
         * listender per verificare limite caratteri
         */
        textFieldCredential.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(final KeyEvent e) {
                if (textFieldCredential.getText().length() >= numMaxChar) {
                    e.consume(); // limita caratteri
                }
            }
        });
    }

    /**
     * Inizializza la gui della finestra credenziale
     *
     * @param title titolo della credenziale richiesta
     */
    public void startGUI(final String title) {
        frame = new JFrame(title);
        frame.setContentPane(this.mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        frame.pack();
        frame.setVisible(true);
        frame.setResizable(false);

        //posiziona frame al centro dello schermo
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }

    /**
     * metodo per ottenere il testo inserito dall'utente del game JTextField
     *
     * @return
     */
    public String getStringUserResponse() {
        return stringUserResponse;
    }

    private void confirmCredential() {
        //bottone conferma premuto
        stringUserResponse = textFieldCredential.getText(); //set variabile credenziale inserita

        //dati inseriti il thread può terminare
        isdataConfirmed = true;

        //distruggi finestra
        frame.setVisible(false);
        frame.dispose();
    }

    /**
     * codice del thread loginRequest
     */
    @Override
    public void run() {
        while (!isdataConfirmed) {
            try {
                Thread.sleep(threadSleep);
                //System.out.println("Inserimento dati login");
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        System.out.println("chiusura thread inserimento credenziale");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(2, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(-1, 200), null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        mainPanel.add(spacer2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, new Dimension(300, -1), null, null, 0, false));
        requestedValue = new JLabel();
        requestedValue.setText("");
        mainPanel.add(requestedValue, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldCredential = new JTextField();
        mainPanel.add(textFieldCredential, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        confirmButton = new JButton();
        confirmButton.setText("Conferma");
        mainPanel.add(confirmButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
